# Generated by Django 3.1.4 on 2020-12-06 17:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
