# Generated by Django 3.1.4 on 2020-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='null.png', upload_to='product_picture'),
        ),
    ]
