# Generated by Django 3.1.4 on 2020-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20201211_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_currency',
            field=models.CharField(choices=[('dollar', '$'), ('euro', '€'), ('egyption_pound', 'L.E')], default='$', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_main_category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Kids', 'kids')], default='Men', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to='product_pictures'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_secondary_category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('coats_jackets', 'Coats/Jackets')], default='Top', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L')], default='S', max_length=20),
        ),
    ]
