# Generated by Django 3.1.4 on 2020-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20201211_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_main_category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='Men', max_length=20),
        ),
    ]
