# Generated by Django 3.1.4 on 2020-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20201211_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
