# Generated by Django 3.1.4 on 2020-12-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reviews',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
