# Generated by Django 3.1.4 on 2020-12-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('product_type', models.CharField(default='shirt', max_length=20)),
                ('in_stock', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('L.E', 'L.E')], default='$', max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=13)),
                ('picture', models.ImageField(default='null.png', upload_to='product_picture/')),
                ('main_category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='Men', max_length=20)),
                ('secondary_category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('coats_jackets', 'Coats/Jackets')], default='Top', max_length=20)),
                ('details', models.CharField(default='', max_length=2000)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerOrSeller', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='App1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
