# Generated by Django 3.1.4 on 2021-01-12 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('in_stock', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('L.E', 'L.E')], default='$', max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=13)),
                ('picture', models.ImageField(default='null.png', upload_to='product_picture/')),
                ('main_category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='Men', max_length=20)),
                ('secondary_category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('coats_jackets', 'Coats/Jackets')], default='Top', max_length=20)),
                ('details', models.CharField(default='', max_length=1999)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, default=None, related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerOrSeller', models.CharField(max_length=30)),
                ('offer_points', models.PositiveIntegerField(blank=True, default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='App1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=99)),
                ('phone_number', models.CharField(max_length=11)),
                ('zip_code', models.CharField(max_length=4)),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('L.E', 'L.E')], default='$', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'COD(Cash on delivery)'), ('credit', 'Credit Card')], default='cod', max_length=20)),
                ('total_cost', models.FloatField(default=0.0, max_length=6)),
                ('new_total_cost', models.FloatField(default=0.0, max_length=10)),
                ('discount_points', models.CharField(max_length=4)),
                ('purchase_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_item_price', models.FloatField(default=100.0, max_length=6)),
                ('purchased', models.BooleanField(default=False)),
                ('in_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
