# Generated by Django 3.1.4 on 2021-01-09 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('zip_code', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('L.E', 'L.E')], default='$', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_approval', models.BooleanField()),
                ('sub_total_cost', models.ManyToManyField(blank=True, to='App1.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
