# Generated by Django 3.1.4 on 2021-01-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sub_total_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_points',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='new_total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
