# Generated by Django 3.1.4 on 2021-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20210110_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_approval',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
