# Generated by Django 3.1.4 on 2021-01-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_product_favourites'),
        ('App1', '0004_auto_20201231_1236'),
    ]

    operations = [
    ]
