# Generated by Django 3.1.4 on 2021-01-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_merge_20210101_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disccount',
        ),
    ]
