# Generated by Django 3.1.4 on 2021-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_remove_product_disccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='offer_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
