# Generated by Django 3.1.4 on 2021-01-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20210110_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
