# Generated by Django 3.1.4 on 2021-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_userinfo_offer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='offer_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
