# Generated by Django 3.1.4 on 2021-01-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20210110_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_item_price',
            field=models.FloatField(default=100.0, max_length=10),
        ),
    ]
