# Generated by Django 3.1.4 on 2021-01-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_auto_20210110_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD(Cash on delivery)'), ('credit', 'Credit Card')], default='cod', max_length=20),
        ),
    ]
