# Generated by Django 2.2.5 on 2021-01-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_approval',
        ),
    ]
