# Generated by Django 3.1.4 on 2021-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_remove_order_purchase_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_total_cost',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_item_price',
            field=models.FloatField(default=100.0, max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0.0, max_length=6),
        ),
    ]
