# Generated by Django 3.1.4 on 2021-01-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_auto_20210110_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='offer_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
