# Generated by Django 3.1.4 on 2021-01-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_userinfo_offer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_points',
            field=models.PositiveIntegerField(default=0, max_length=4),
        ),
    ]
