# Generated by Django 3.1.4 on 2021-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_auto_20210110_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_total_cost',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
