# Generated by Django 3.1.4 on 2021-01-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_order_new_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='points',
            new_name='discount_points',
        ),
    ]
