# Generated by Django 3.1.4 on 2021-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_auto_20210110_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_points',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=4),
        ),
    ]
