# Generated by Django 3.1.4 on 2020-12-06 15:55

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('shirt', 'Shirt'), ('trousers', 'Trousers'), ('dess', 'Dress'), ('skirt', 'Skirt')], default='shirt', max_length=20)),
                ('in_stock', models.PositiveIntegerField()),
                ('Color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=13)),
                ('picture', models.ImageField(upload_to='product_picture')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
