# Generated by Django 3.1.4 on 2020-12-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='shirt', max_length=20),
        ),
    ]
