# Generated by Django 3.1.4 on 2020-12-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20201206_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
    ]
