# Generated by Django 3.1.4 on 2020-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_remove_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
