# Generated by Django 3.1.4 on 2020-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='null.png', upload_to='product_picture/'),
        ),
    ]
